---
fig_height: 3
fig_width: 5
output:
  html_document:
    theme: yeti
params:
  hourly_rate: 15
  client_hourly_rate: 30
  new_hourly_rate: 20
  new_client_hourly_rate: 40
  start_date: ''
  end_date: ''
  fetch_new: TRUE
  old_bank: TRUE
---

```{r, echo = FALSE, warning = FALSE, message = FALSE, comment = NA, error= FALSE, cache = F}
# No scientific notation
options(scipen=999)
library(Quandl)
library(knitr)
library(tidyverse)
library(gsheet)
library(DT)
library(tidyr)
library(ggthemes)
# Basic knitr options
opts_chunk$set(comment = NA, 
               echo = FALSE, 
               warning = FALSE, 
               message = FALSE, 
               error = TRUE, 
               cache = FALSE)
```

```{r}
# Specify paramaters
for (i in 1:length(params)){
  assign(names(params)[i],
         params[[i]],
         env = .GlobalEnv)
}

creation_date <- as.Date(Sys.Date())
```

```{r}
file_name <- paste0(creation_date, '.RData')
has <- function(x){
  out <- FALSE
  if(!is.null(x)){
    if(x != ''){
      out <- TRUE
    }
  }
  return(out)
}

has_start_date <- has(start_date)
has_end_date <- has(end_date)
if(!has_start_date){
  start_date <- as.Date('2015-01-01')
} else{
  start_date <- as.Date(start_date)
}
if(!has_end_date){
  end_date <- as.Date(Sys.Date())
} else {
  end_date <- as.Date(end_date)
}

# if(file_name %in% dir('backups') & !fetch_new){
#   load(paste0('backups/', file_name))
# } else {
  # Get accounting data
  expenses <- gsheet2tbl('https://docs.google.com/spreadsheets/d/1RABWgak2e2i2blu1tLUmbNHagJGrh7MPbivuXB2TCDM/edit#gid=0')
  income <- gsheet2tbl('https://docs.google.com/spreadsheets/d/1RABWgak2e2i2blu1tLUmbNHagJGrh7MPbivuXB2TCDM/edit#gid=684913063')
  hours <- gsheet2tbl('https://docs.google.com/spreadsheets/d/1RABWgak2e2i2blu1tLUmbNHagJGrh7MPbivuXB2TCDM/edit#gid=565858805')
  hours2019 <- gsheet2tbl('https://docs.google.com/spreadsheets/d/1RABWgak2e2i2blu1tLUmbNHagJGrh7MPbivuXB2TCDM/edit#gid=335157130')
  hours <- bind_rows(hours, hours2019)
  wages_paid <- gsheet2tbl('https://docs.google.com/spreadsheets/d/1RABWgak2e2i2blu1tLUmbNHagJGrh7MPbivuXB2TCDM/edit#gid=1319225983')
#   save(expenses, income, hours,
#        file = paste0('backups/', file_name))
# }
expenses$date <- as.Date(expenses$date, format = '%m/%d/%Y')
hours$date <- as.Date(hours$date, format = '%m/%d/%Y')
income$date <- as.Date(income$date, format = '%m/%d/%Y')
wages_paid$date <- as.Date(wages_paid$date, format = '%m/%d/%Y')
# Make all data frames
expenses <- data.frame(expenses)
hours <- data.frame(hours)
income <- data.frame(income)
wages_paid <- data.frame(wages_paid)
# Get currency data
currency <- Quandl("BOE/XUDLCDD", 
                   api_key="dRx5HohjAeCyjfTMxtz4")
names(currency) <- c('date', 'usd_to_cad')
# Expand out to sys date if needed
currency <- left_join(data_frame(date = seq(min(currency$date),
                                 Sys.Date(),
                                 by = 1)),
                      currency) 
currency <- currency %>% arrange(date) %>%
  tidyr::fill(usd_to_cad, .direction = 'down')
# Create usd columns
expenses <-
  left_join(expenses, currency,
            by = 'date') %>%
  mutate(usd = ifelse(currency == 'CAD',
                      amount / usd_to_cad,
                      amount))
income <- left_join(income, currency,
                    by = 'date') %>%
  mutate(usd = ifelse(currency == 'CAD',
                      amount / usd_to_cad,
                      amount))
wages_paid <- left_join(wages_paid, currency,
                         by = 'date') %>%
  mutate(usd = ifelse(currency == 'CAD',
                      amount / usd_to_cad,
                      amount))

x = hours %>%
  mutate(status = ifelse(high_priority, 'External', 'Internal')) %>%
  group_by(status, name) %>%
  summarise(hours = sum(total_hours)) %>%
  ungroup
# ggplot(data = x,
#        aes(x = name,
#            y = hours,
#            group = status,
#            fill = status)) +
#   geom_bar(stat = 'identity',
#            position = 'dodge') +
#   databrew::theme_databrew()
```

```{r, results = 'hide'}
# Get amount in Canadian bank
source('accounting_get_bank_data.R')
if(old_bank){
  bank <- read_csv('data/bank_value.csv')
} else {
  bank <- get_cad()
}


# Convert to usd
bank$cad <- bank$value
bank <- left_join(bank, currency)
bank$usd <- bank$cad / bank$usd_to_cad
bank$usd_to_cad <- NULL
bank <- bank %>% arrange(date)
# {.tabset .tabset-fade .tabset-pills}
```


# Databrew internal accounting 


## Non-wage expenses over time

```{r, results = 'asis'}
# Get all expenditures
x <- expenses %>%
  filter(!is.na(reimbursed)) %>%
  filter(!reimbursed) %>%
  dplyr::select(date, usd, item) %>%
  # mutate(usd = -1 * usd) %>%
  # bind_rows(
  #   income %>%
  #     dplyr::select(date, usd)
  # ) %>%
  arrange(date) %>%
  mutate(balance = cumsum(usd))
x <- left_join(data_frame(date = seq(min(x$date),
                                     Sys.Date(),
                                     by = 1)),
               x,
               by = 'date') %>%
  arrange(date)
x <- x %>%
  tidyr::fill(balance, .direction = 'down')

ggplot(data = x,
       aes(x = date,
           y = balance)) +
  geom_step(alpha = 0.7) +
  geom_hline(yintercept = 0, col = 'black',
             lty = 3, alpha = 0.6) +
  theme_fivethirtyeight() +
  labs(x = 'Date',
       y = 'Balance',
       title = paste0('All expenses: ', round(dplyr::last(x$balance)), ' USD'),
       subtitle = '(Ignores hours worked and income)')
```


```{r, eval = FALSE}
DT::datatable(x %>% filter(!is.na(usd)) %>%
                mutate(usd = round(usd, digits = 2),
                       balance = round(balance, digits = 2)))
```

## Bank balance

```{r}
current_balance <- dplyr::last(x$balance) + bank$usd
```

Our current balance in the bank is `r round(dplyr::last(bank$cad))` CAD (`r round(dplyr::last(bank$usd))` USD).



```{r}
# Define date of changing to increased wages
change_date <- as.Date('2019-07-01')
names_df <- data.frame(name = c(sort(unique(hours$name))))
# Get all hours worked which have not yet been paid
hours_money <-
  hours %>%
  # filter(!paid_to_worker) %>%
  group_by(name) %>%
  summarise(total_hours_old = sum(total_hours[date < change_date]),
            total_hours_new = sum(total_hours[date >= change_date]))
hours_money_client <-
  hours %>%
  filter(billable_to_client) %>%
  group_by(name) %>%
  summarise(total_hours_client_old = sum(total_hours[date < change_date]),
            total_hours_client_new = sum(total_hours[date >= change_date]))
hours_money <- left_join(x = hours_money,
                         y = hours_money_client,
                         by = 'name')
hours_money <- left_join(names_df, hours_money) %>% 
  mutate(total_hours_old = ifelse(is.na(total_hours_old), 0, total_hours_old),
         total_hours_new = ifelse(is.na(total_hours_new), 0, total_hours_new),
         total_hours_client_old = ifelse(is.na(total_hours_client_old), 0, total_hours_client_old),
         total_hours_client_new = ifelse(is.na(total_hours_client_new), 0, total_hours_client_new))
hours_money <- hours_money %>%
  mutate(total_hours = total_hours_old + total_hours_new,
         total_hours_client = total_hours_client_old + total_hours_client_new) %>%
  mutate(percent_client = total_hours_client / total_hours * 100) %>%
  mutate(total_hours_internal = total_hours - total_hours_client) %>%
  mutate(total_hours_internal_new = total_hours_new - total_hours_client_new,
         total_hours_internal_old = total_hours_old - total_hours_client_old)

# Get all expenditures by any person which have not yet been reimbursed
ex_money <- expenses %>%
  filter(!reimbursed) %>%
  group_by(name = payment_by) %>%
  summarise(total_ex = sum(usd))
ex_money <- left_join(names_df, ex_money) %>% mutate(total_ex = ifelse(is.na(total_ex), 0, total_ex))
# Get total income paid to any one person which should have been collective
in_money <- income %>%
  group_by(name = paid_to) %>%
  summarise(total_in = sum(usd))
in_money <- left_join(names_df, in_money) %>% mutate(total_in = ifelse(is.na(total_in), 0, total_in))
# Get wages paid and not yet reimbursed
out_wages <- wages_paid %>%
  group_by(name) %>%
  summarise(wages_paid = sum(usd))
out_wages <- left_join(names_df, out_wages) %>% mutate(wages_paid = ifelse(is.na(wages_paid), 0, wages_paid))

# Join all together
together <- left_join(hours_money, ex_money) %>% left_join(in_money) %>% left_join(out_wages)
# Round all columns
together <- together %>%
  mutate(total_hours = round(total_hours, digits = 2),
         total_ex = round(total_ex, digits = 2),
         total_in = round(total_in, digits = 2),
         wages_paid = round(wages_paid, digits = 2)) %>%
  rename(expenditures_absorbed = total_ex,
         income_absorbed = total_in)

# Convert hours to usd
x <- together
wage <- params$hourly_rate
new_wage <- params$new_hourly_rate
client_wage <- params$client_hourly_rate
new_client_wage <- params$new_client_hourly_rate
x <- x %>%
  mutate(wages_earned = 
           (total_hours_client_new * new_client_wage) +
           (total_hours_client_old * client_wage) +
           (total_hours_internal_new * new_wage) +
           (total_hours_internal_old * wage))



# Calculate current balance
together_reactive <-  x %>%
  mutate(balance = wages_earned - wages_paid + expenditures_absorbed - income_absorbed)
```

### Overall balance (ie, balance after wages)

<large>
<strong>

```{r, results = 'asis'}
bank_val <- round(dplyr::last(bank$usd), digits = 2)
x <- together_reactive
x <- x %>%
  summarise(balance = sum(balance)) %>%
  mutate(balance_numeric = balance) %>%
  mutate(balance = paste0(balance, ifelse(balance > 0, ' in the red', ' in the black')))  %>%
  mutate(balance_bank = balance_numeric - bank_val) %>%
  mutate(balance_bank_text = paste0(abs(balance_bank), ifelse(balance_bank > 0, ' in the red', ' in the black')))

cat(paste0('Not counting money in the bank, paying wages will make us ', x$balance, '.'))
cat(paste0('But, we have ', bank_val, ' USD in the bank.'))
cat(paste0('If we empty the bank account in wages, we are ', x$balance_bank_text, '.'))
```

</large>
</strong>


## Hours worked over time 

```{r}
x <- hours %>%
  group_by(date, name) %>%
  summarise(hours = sum(total_hours)) %>%
  ungroup %>%
  arrange(date) %>%
  group_by(name) %>%
  mutate(cum_hours = cumsum(hours)) %>%
  ungroup

cols <- colorRampPalette(RColorBrewer::brewer.pal(n = 8, 'Spectral'))(length(unique(x$name)))
ggplot(data = x,
       aes(x = date,
           y = cum_hours,
           color = name)) +
  geom_line(alpha = 1, size = 1) +
  theme_fivethirtyeight() +
  labs(x = 'Date',
       y = 'Cumulative hours',
       title = 'Hours worked',
       subtitle = 'Not including "non-shared" hours (ie, Xing\'s work for YouthRex)') +
  scale_color_manual(name = '',
                     values = cols)
```

```{r, eval = FALSE}
DT::datatable(x)
```

### How much employees are owed

```{r}
x <- together_reactive
ggplot(data = x,
       aes(x = name,
           y = balance)) +
  geom_bar(stat = 'identity',
           fill = 'darkblue',
           alpha = 0.6) +
  geom_label(aes(label = round(balance))) +
  theme_fivethirtyeight() +
  labs(x = 'Who',
       y = 'USD')

# DT::datatable(together_reactive)
databrew::prettify(together_reactive)
```


```{r, results = 'asis'}
cat(paste0('## Appendix: raw data '))
```

```{r, results = 'asis'}
cat(paste0('### Expenses: raw data '))
```

```{r}
DT::datatable(expenses)
```


```{r, results = 'asis'}
cat(paste0('### Hours: raw data '))
```

```{r}
DT::datatable(hours)
```

```{r, results = 'asis'}
cat(paste0('### Income: raw data '))
```

```{r}
DT::datatable(income)
```
